image: node:latest

stages:
  # - install
  # - build
  # - audit
  - test

# cache:
#   paths:
#     - node_modules/

# install:
#   stage: install
#   script:
#     - npm run install

# build-code-job:
#   stage: build
#   script:
#     - echo "Check the ruby version, then build some Ruby project files:"
#     - ruby -v
#     - rake

test-unit:
  stage: test
  script:
    - npm run install
    - npm run test:unit

# audit-snyk:
#   stage: audit
#   script:
#    - npm run audit:snyk

# audit-npm:
#   stage: audit
#   script:
#    - npm run audit:npm

# test-code-job2:
#   stage: test
#   script:
#     - echo "If the files are built successfully, test other files with a different command:"
#     - rake test2