services:
    youtify:
        build: . # Build from Dockerfile in this dir
        environment:
            - "SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}"
            - "SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}"
            - "SPOTIFY_USER=${SPOTIFY_USER}"
            - "SPOTIFY_PASS=${SPOTIFY_PASS}"
        volumes:
            # "host:container"
            - "./data:/usr/src/app/src/data"
        